Break CI tests into multiple parallel workflows

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,33 +1,80 @@
-format_version: "11"
+---
+format_version: "14"
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: other
 
+trigger_map:
+- push_branch: master
+  pipeline: ci
+- pull_request_source_branch: "*"
+  pipeline: ci
+
+pipelines:
+  ci:
+    stages:
+    - run_tests: {}
+
+stages:
+  run_tests:
+    workflows:
+    - lint: {}
+    - unit_test: {}
+    - integration_test: {}
+    - test_binary_build: {}
+
 app:
   envs:
-  - BIN_NAME: bitrise
+  - SRC_DIR_IN_GOPATH: "$GOPATH/src/github.com/bitrise-io/bitrise"
 
 workflows:
-  check:
+  lint:
     steps:
+    - script@1:
+        title: Setup YAML lint
+        inputs:
+        - script_file_path:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -ex
+            
+            apt-get --assume-yes install python3.8-venv
+    - change-workdir:
+        inputs:
+        - path: "${SRC_DIR_IN_GOPATH}"
+    - git-clone:
+        inputs:
+        - fetch_tags: 'yes'
     - git::https://github.com/bitrise-steplib/steps-check.git:
         inputs:
         - workflow: lint
         - skip_step_yml_validation: "yes"
+    - deploy-to-bitrise-io: {}
+
+  unit_test:
+    steps:
+    - change-workdir:
+        inputs:
+        - path: "${SRC_DIR_IN_GOPATH}"
+    - git-clone:
+        inputs:
+        - fetch_tags: 'yes'
     - go-list: { }
     - script:
         title: Go test
         inputs:
         - content: go test -p 1 $BITRISE_GO_PACKAGES
-
-  test:
-    title: Runs tests
-    after_run:
-    - check
-    - integration-test
+    - deploy-to-bitrise-io: {}
 
   integration-test:
     title: Runs integration tests
     steps:
+    - change-workdir:
+        inputs:
+        - path: "${SRC_DIR_IN_GOPATH}"
+    - git-clone:
+        inputs:
+        - fetch_tags: 'yes'
     - script:
         title: Run integration tests
         inputs:
@@ -49,37 +96,31 @@ workflows:
             if [ "$(uname)" == "Linux" ]; then
                 go test -v ./_tests/integration/ --tags linux_only
             fi
+    - deploy-to-bitrise-io: {}
 
-  create-release:
-    description: Creates Linux and Darwin binaries, then publishes a GitHub release
-    envs:
-    - GITHUB_TOKEN: $GIT_BOT_USER_ACCESS_TOKEN  # Goreleaser expects this env var
-    steps:
-    - script:
-        title: Fetch GCS bucket credentials
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-
-            echo "$GCS_BITRISE_CLI_BUCKET_CREDENTIALS" > /tmp/gcs_service_account.json
-            # Goreleaser expects this env var:
-            envman add --key GOOGLE_APPLICATION_CREDENTIALS --value /tmp/gcs_service_account.json
-    - script:
-        title: Goreleaser (create binaries + publish to GH)
-        deps:
-          brew:
-          - name: goreleaser
-        inputs:
-        - content: |
-            #!/usr/bin/env bash
-            set -ex
-
-            goreleaser release
-
-  test-binary-build:
+  test_binary_build:
     description: Tests the release build process by creating a snapshot release (without publishing)
     steps:
+    - script@1:
+        title: Set up Goreleaser
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            wget -O /tmp/goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_1.19.2_amd64.deb
+            sudo dpkg -i /tmp/goreleaser.deb
+    - change-workdir:
+        inputs:
+        - path: "${SRC_DIR_IN_GOPATH}"
+    - git-clone:
+        inputs:
+        - fetch_tags: 'yes'
     - script:
         title: Goreleaser (create snapshot binaries)
         deps:
@@ -91,39 +132,9 @@ workflows:
             set -ex
 
             goreleaser release --snapshot --rm-dist
+    - deploy-to-bitrise-io: {}
 
-  noop:
-    title: Noop
-    description: Empty workflow for quick testing
-
-  fail-test:
-    title: Fails
-    description: Workflow will fail
-    steps:
-    - script:
-        title: Success
-        inputs:
-        - content: |-
-            set -ex
-            exit 0
-    - script:
-        title: Fail wit exit code 2
-        inputs:
-        - content: |-
-            set -ex
-            exit 2
-    - script:
-        title: Skippable fail with exit code 2
-        is_always_run: true
-        is_skippable: true
-        inputs:
-        - content: |-
-            set -ex
-            exit 2
-    - script:
-        title: Skipping success
-        is_always_run: false
-        inputs:
-        - content: |-
-            set -ex
-            exit 0
+meta:
+  bitrise.io:
+    machine_type_id: elite-xl
+    stack: linux-docker-android-20.04
