a fail workflow example

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -11,6 +11,7 @@ app:
       is_expand: no
 
 workflows:
+  # ----- Main (real) Workflows -----
   test:
     steps:
     - script:
@@ -51,3 +52,32 @@ workflows:
             set -e
             godep restore
             go install
+
+  # ----- Other, test workflows -----
+  fail:
+    # this workflow is a test for failed steps/workflows,
+    #  it'll fail
+    steps:
+      - script:
+          title: "ok"
+      - script:
+          title: "fail"
+          inputs:
+          - content: |
+              #/bin/bash
+              set -v
+              exit 1
+      - script:
+          title: "ok"
+          inputs:
+          - content: |
+              #/bin/bash
+              echo "-----> This should NOT be printed!!"
+          is_always_run: false
+      - script:
+          title: "ok"
+          inputs:
+          - content: |
+              #/bin/bash
+              echo "-----> This should be printed!!"
+          is_always_run: true
