Update binary build tests

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -67,6 +67,14 @@ workflows:
 
   test_binary_build_macos:
     steps:
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -ex
+
+            go install github.com/goreleaser/goreleaser@latest
     - bundle::test_binary_build: { }
     meta:
       bitrise.io:
@@ -75,6 +83,20 @@ workflows:
 
   test_binary_build_linux:
     steps:
+    - script@1:
+        title: Set up Goreleaser
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            wget -O /tmp/goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_1.19.2_amd64.deb
+            sudo dpkg -i /tmp/goreleaser.deb
     - bundle::test_binary_build: { }
     meta:
       bitrise.io:
@@ -158,14 +180,6 @@ step_bundles:
 
   test_binary_build:
     steps:
-    - script@1:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -ex
-
-            go install github.com/goreleaser/goreleaser@latest
     - git-clone@8:
         inputs:
         - fetch_tags: "yes"
