go version

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -469,6 +469,27 @@ step_bundles:
 
   install_dependencies:
     steps:
+    - script@1:
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # make pipelines' return status equal the last command to exit with
+            a non-zero status, or zero if all commands exit successfully
+
+            set -o pipefail
+
+            # debug log
+
+            set -x
+
+
+            go version
+        title: Check go version
     - bitrise-run@0:
         inputs:
         - workflow_id: unpin-go-version
@@ -493,7 +514,27 @@ step_bundles:
 
 
             bitrise tools setup --config .tool-versions
-        title: Install .tool-versions dependencies
+    - script@1:
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # make pipelines' return status equal the last command to exit with
+            a non-zero status, or zero if all commands exit successfully
+
+            set -o pipefail
+
+            # debug log
+
+            set -x
+
+
+            go version
+        title: Check go version
     inputs:
     - IGNORE_CUSTOM_GOLANG: "false"
       opts:
