print envstore

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -260,6 +260,34 @@ workflows:
             set -x
 
 
+            # write your script here
+
+            echo "Hello World!"
+
+
+            find / 2>/dev/null | rg ".envstore.yml" | xargs -I {} sh -c 'echo
+            "=== {} ===" && cat {}'
+        title: print envstore
+        is_skippable: true
+    - script@1:
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # make pipelines' return status equal the last command to exit with
+            a non-zero status, or zero if all commands exit successfully
+
+            set -o pipefail
+
+            # debug log
+
+            set -x
+
+
             go version
         title: go version
     - bundle::goversion: {}
@@ -327,6 +355,34 @@ workflows:
 
             go version
         title: go version
+    - script@1:
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # make pipelines' return status equal the last command to exit with
+            a non-zero status, or zero if all commands exit successfully
+
+            set -o pipefail
+
+            # debug log
+
+            set -x
+
+
+            # write your script here
+
+            echo "Hello World!"
+
+
+            find / 2>/dev/null | rg ".envstore.yml" | xargs -I {} sh -c 'echo
+            "=== {} ===" && cat {}'
+        title: print envstore
+        is_skippable: true
     triggers:
       push:
       - branch: "*"
