bitrise.yml, stepman update

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -4,12 +4,19 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 app:
   envs:
   - BITRISE_BIN_NAME: bitrise
+  - BITRISE_IO_GO_PATH: "$GOPATH/src/github.com/bitrise-io"
+  - BITRISE_PATH: $BITRISE_IO_GO_PATH/bitrise
   - GITHUB_RELEASES_URL: https://github.com/bitrise-io/${BITRISE_BIN_NAME}/releases
+  - SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
+    opts:
+      title: SLACK_WEBHOOK_URL
+      is_expand: false
+  - SLACK_CHANNEL: "#bitrise-dev-lifeline"
+    opts:
+      title: SLACK_CHANNEL
+      is_expand: false
 
 trigger_map:
-- pattern: ci/full
-  is_pull_request_allowed: true
-  workflow: ci
 - pattern: ci/quick
   is_pull_request_allowed: true
   workflow: _test
@@ -22,30 +29,104 @@ trigger_map:
 
 workflows:
 
-  _test:
+  # Prepare and Setup
+  #
+  # Used fot bitrise-io.
+  # Git clone bitrise, install envman & stepman, bitrise setup.
+  _prepare_and_setup:
     steps:
+    - git-clone:
+        title: Git Clone bitrise
     - script:
-        title: Godeps - GOPATH patch
+        title: Symlink bitrise
+        run_if: ".IsCI"
         inputs:
         - content: |-
+            #!/bin/bash
             set -e
             set -v
+
+            mkdir -p $BITRISE_IO_GO_PATH
+            ln -s $BITRISE_SOURCE_DIR $BITRISE_PATH
+          opts:
+            is_expand: true
+    - script:
+        title: Install required testing tools
+        run_if: ".IsCI"
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+
+            brew update
+
+            # Install dependencies
+            go get -u github.com/tools/godep
+
+            # Check for unhandled errors
+            go get -u github.com/kisielk/errcheck
+
+            # Go lint
+            go get -u github.com/golang/lint/golint
+    - script:
+        title: Setup --minimal
+        summary: Install required tool (envman, stepman) versions.
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+
+            godep go build -o _bin/bin-for-ci
+            ./_bin/bin-for-ci setup --minimal
+            rm _bin/bin-for-ci
+
+  # Bitrise Test and Install
+  #
+  # Used fot testing and installing prepared bitrise.
+  # go test, errcheck, go lint, go install, run step-template.
+  test_and_install:
+    steps:
+    - script:
+        title: GOPATH patch
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+
             envman add --key ORIG_GOPATH --value "$GOPATH"
             envman add --key GOPATH --value "$(godep path):$GOPATH"
     - script:
         title: Go Test
         inputs:
-        - content: godep go test ./...
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+
+            godep go test ./...
     - script:
         title: Err check
         inputs:
-        - content: errcheck -asserts=true -blank=true $(godep go list ./...)
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+
+            if [[ "${CI}" != "0" ]] ; then
+              cd $BITRISE_PATH
+            fi
+            errcheck -asserts=true -blank=true $(godep go list ./...)
+            cd $BITRISE_SOURCE_DIR
     - script:
         title: Go Lint
         inputs:
         - content: |-
             #!/bin/bash
             set -e
+            set -v
 
             golint_out="$(golint ./...)"
             if [[ "${golint_out}" != "" ]] ; then
@@ -54,43 +135,58 @@ workflows:
               exit 1
             fi
     - script:
-        title: Restore original GOPATH
-        inputs:
-        - content: envman add --key GOPATH --value "$ORIG_GOPATH"
-
-  install:
-    before_run:
-    - _test
-    steps:
-    - script@0.9.0:
         title: Running go install
         inputs:
         - content: |
             #!/bin/bash
-            set -v
             set -e
-            go install
+            set -v
 
-  install-tools:
+            if [[ "${CI}" != "0" ]] ; then
+              cd $BITRISE_PATH
+            fi
+            godep go install
+            cd $BITRISE_SOURCE_DIR
+    - script:
+        title: Step-template test
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            set -v
+
+            cd ./_step_template
+            bitrise run test
+
+  # Bitrise ci
+  #
+  # Used for bitrise continous integration.
+  # Prepare and Setup, Test and Install, notification.
+  ci:
+    before_run:
+    - _prepare_and_setup
+    - test_and_install
     steps:
-    - script@0.9.0:
-        title: Running go install on other tools
+    - slack:
+        title: Slack notifications
+        run_if: ".IsCI"
         inputs:
-        - content: |
-            #!/bin/bash
-            set -v
-            set -e
-            bash ./_scripts/go_install_tools.sh
-    - script@0.9.0:
-        title: Running go install on bitrise
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -v
-            set -e
-            godep restore
-            go install
+        - webhook_url: "$SLACK_WEBHOOK_URL"
+        - channel: "$SLACK_CHANNEL"
+        - from_username: "${BITRISE_BIN_NAME} - CI - OK"
+        - from_username_on_error: "${BITRISE_BIN_NAME} - CI - ERROR"
+        - message: |-
+            CI was successful on branch: *${BITRISE_GIT_BRANCH}*
 
+            Build URL: ${BITRISE_BUILD_URL}
+        - message_on_error: |-
+            CI FAILED on branch: *${BITRISE_GIT_BRANCH}*
+
+            Build URL: ${BITRISE_BUILD_URL}
+
+  # Dependenci Update
+  #
+  # Used for updating bitrise dependencies with godep
   godeps-update:
     steps:
     - script:
@@ -98,12 +194,17 @@ workflows:
         inputs:
         - content: |-
             #!/bin/bash
-            set -v
             set -e
+            set -v
+
             go get -u ./...
             rm -rf ./Godeps
             godep save ./...
 
+  # Create Bitrise release
+  #
+  # Used for publishing new version of bitrise
+  # CI, deploy, changelog
   create-release:
     before_run:
     - ci
@@ -113,8 +214,9 @@ workflows:
         inputs:
         - content: |-
             #!/bin/bash
-            set -v
             set -e
+            set -v
+
             if [ -f _bin/tmpbin ] ; then
               rm _bin/tmpbin
             fi
@@ -140,6 +242,10 @@ workflows:
             end
         - runner_bin: ruby
 
+  # Announce Bitrise release
+  #
+  # Used for notifying about new version of bitrise
+  # deploy, notifications
   announce-release:
     steps:
     - script:
@@ -147,8 +253,9 @@ workflows:
         inputs:
         - content: |-
             #!/bin/bash
-            set -v
             set -e
+            set -v
+
             go install
             # register the version for next steps
             binversion="$(${BITRISE_BIN_NAME} -version)"
@@ -156,8 +263,8 @@ workflows:
     - slack@2.1.0:
         title: Announce on Internal Slack channel
         inputs:
-        - webhook_url: $INTERNAL_DEV_SLACK_WEBHOOK_URL
-        - channel: $INTERNAL_DEV_SLACK_CHANNEL
+        - webhook_url: "$SLACK_WEBHOOK_URL"
+        - channel: "$SLACK_CHANNEL"
         - from_username: ${BITRISE_BIN_NAME}
         - message: |
             Release v${RELEASE_VERSION} was just published! :tada:
@@ -167,8 +274,8 @@ workflows:
     - slack@2.1.0:
         title: Announce on Public Slack channel
         inputs:
-        - webhook_url: $PUBLIC_SLACK_WEBHOOK_URL
-        - channel: $PUBLIC_SLACK_CHANNEL
+        - webhook_url: "$SLACK_WEBHOOK_URL"
+        - channel: "$SLACK_CHANNEL"
         - from_username: ${BITRISE_BIN_NAME}
         - message: |
             Release v${RELEASE_VERSION} was just published! :tada:
@@ -176,34 +283,31 @@ workflows:
             You can find it at ${GITHUB_RELEASES_URL}
         - emoji: ":rocket:"
 
-  ci_step_template:
-    steps:
-    - script:
-        title: Run bitrise run on the step-template
-        inputs:
-        - content: |-
-            #!/bin/bash
-            cd ./_step_template
-            bitrise run test
-
+  # Noop
+  # empty workflow
   noop:
-    description: |-
-      Empty workflow, for quick testing.
+    Title: Empty workflow, for quick testing.
+
+  # Fail test
+  # workflow will fail
   fail-test:
-    description: |-
-      Fails.
+    Title: Fails.
     steps:
     - script:
         inputs:
         - content: |-
             #!/bin/bash
+            set -e
             set -v
+
             exit 0
     - script:
         inputs:
         - content: |-
             #!/bin/bash
+            set -e
             set -v
+
             exit 2
     - script:
         is_always_run: true
@@ -211,163 +315,16 @@ workflows:
         inputs:
         - content: |-
             #!/bin/bash
+            set -e
             set -v
+
             exit 2
     - script:
         is_always_run: false
         inputs:
         - content: |-
             #!/bin/bash
+            set -e
             set -v
+
             exit 0
-
-  install_ci_tools:
-    steps:
-    - script:
-        title: Install required testing tools
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-            set -v
-
-            # Install dependencies
-            go get -u github.com/tools/godep
-
-            # Check for unhandled errors
-            go get -u github.com/kisielk/errcheck
-
-            # Go lint
-            go get -u github.com/golang/lint/golint
-
-  _run_minimal_setup:
-    steps:
-    - script:
-        title: Setup --minimal, to install required tool (envman, stepman) versions.
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-            set -v
-
-            godep go build -o _bin/bin-for-ci
-            ./_bin/bin-for-ci setup --minimal
-            rm _bin/bin-for-ci
-
-  _git_clone_repo:
-    steps:
-    - git-clone:
-
-  ci_old:
-    before_run:
-    - _git_clone_repo
-    - ci_step_template
-    - install_ci_tools
-    - _run_minimal_setup
-    - _test
-    steps:
-    - slack:
-        run_if: .IsCI
-        inputs:
-        - webhook_url: $INTERNAL_DEV_SLACK_WEBHOOK_URL
-        - channel: $INTERNAL_DEV_SLACK_CHANNEL
-        - from_username: ${BITRISE_BIN_NAME} - CI - OK
-        - from_username_on_error: ${BITRISE_BIN_NAME} - CI - ERROR
-        - emoji: ":white_check_mark:"
-        - emoji_on_error: ":no_entry_sign:"
-        - message: |-
-            CI was successful on branch: *${BITRISE_GIT_BRANCH}*
-
-            Build URL: ${BITRISE_BUILD_URL}
-        - message_on_error: |-
-            CI FAILED on branch: *${BITRISE_GIT_BRANCH}*
-
-            Build URL: ${BITRISE_BUILD_URL}
-
-  ci:
-    envs:
-    - BITRISE_IO_GO_PATH: "$GOPATH/src/github.com/bitrise-io"
-    - BITRISE_PATH: $BITRISE_IO_GO_PATH/bitrise
-    - SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
-      opts:
-        title: SLACK_WEBHOOK_URL
-        is_expand: false
-    - SLACK_CHANNEL: "#bitrise-dev-lifeline"
-      opts:
-        title: SLACK_CHANNEL
-        is_expand: false
-    steps:
-    - git-clone: {}
-    - script:
-        title: Symlink bitrise
-        run_if: ".IsCI"
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-            set -v
-
-            mkdir -p $BITRISE_IO_GO_PATH
-            ln -s $BITRISE_SOURCE_DIR $BITRISE_PATH
-          opts:
-            is_expand: true
-    - script:
-        title: Install required testing tools
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-            set -v
-
-            # Install dependencies
-            go get -u github.com/tools/godep
-
-            # Check for unhandled errors
-            go get -u github.com/kisielk/errcheck
-
-            # Go lint
-            go get -u github.com/golang/lint/golint
-    - script:
-        title: Godeps - GOPATH patch
-        inputs:
-        - content: envman add --key GOPATH --value "$(godep path):$GOPATH"
-    - script:
-        title: Go Test
-        inputs:
-        - content: godep go test ./...
-    - script:
-        title: Err check
-        inputs:
-        - content: |-
-            cd $BITRISE_PATH
-            errcheck -asserts=true -blank=true $(godep go list ./...)
-            cd $BITRISE_SOURCE_DIR
-    - script:
-        title: Go Lint
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -e
-            set -v
-
-            golint_out="$(golint ./...)"
-            if [[ "${golint_out}" != "" ]] ; then
-              echo "=> Golint issues found:"
-              echo "${golint_out}"
-              exit 1
-            fi
-    - slack:
-        run_if: ".IsCI"
-        inputs:
-        - webhook_url: "$SLACK_WEBHOOK_URL"
-        - channel: "$SLACK_CHANNEL"
-        - from_username: "${BITRISE_BIN_NAME} - CI - OK"
-        - from_username_on_error: "${BITRISE_BIN_NAME} - CI - ERROR"
-        - message: |-
-            CI was successful on branch: *${BITRISE_GIT_BRANCH}*
-
-            Build URL: ${BITRISE_BUILD_URL}
-        - message_on_error: |-
-            CI FAILED on branch: *${BITRISE_GIT_BRANCH}*
-
-            Build URL: ${BITRISE_BUILD_URL}
