Fix build status env with step bundles

diff --git a/_tests/integration/workflow_run_envs_test_bitrise.yml b/_tests/integration/workflow_run_envs_test_bitrise.yml
--- a/_tests/integration/workflow_run_envs_test_bitrise.yml
+++ b/_tests/integration/workflow_run_envs_test_bitrise.yml
@@ -2,6 +2,27 @@
 format_version: "17"
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
+step_bundles:
+  _failing_bundle:
+    steps:
+    - script:
+        title: Failing step
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            echo "Failing step"
+            exit 2
+    - script:
+        title: Print failing step and failure reason envs (inside bundle)
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            echo "Build status failing inside bundle"
+            echo "BITRISE_BUILD_STATUS: $BITRISE_BUILD_STATUS"
+
 workflows:
   workflow_run_envs_test:
     steps:
@@ -57,6 +78,19 @@ workflows:
             #!/bin/bash
             set -e
             echo "Skipped step"
+
+  bundle_run_envs_test:
+    steps:
+    - bundle::_failing_bundle
+    - script:
+        title: Print failing step and failure reason envs (after bundle)
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+            echo "Build status failing after bundle"
+            echo "BITRISE_BUILD_STATUS: $BITRISE_BUILD_STATUS"
 
   before_after_workflow_run_envs_test:
     before_run:
